### PR TITLE
Allow user to search by DOI, LIDVID, or partial and List results

### LINKED ISSUE #25: As a user, I want to search for a DOI and associated metadata by LID/LIDVID
...so i can use the DOI in a citation or trace back from a DOI to an associated bundle, collection, or product LID/LIDVID

## Details
Web page that displays all available DOIs in the PDS.

NOTE: As much as possible, let's try to replicate the search functionality implemented in the DOI UI.

### Initial State
This page should appear as the landing page for the DOI UI. From this page, it should display a table of all PDS DOIs, ordered by latest update date.

### Search
Here is a quick wireframe of what I am thinking about the UI layout. This will go at https://pds.nasa.gov/datastandards/citing/doi .

Additionally, it should provide a basic search capability where a user can:
1. (this ticket) enter a LID/LIDVID and get the results associated DOI metadata
2. (see #33) enter a DOI and get the resulting associated DOI metadata

 The LID or LIDVID can come in several forms:
* bundle LID / LIDVID - `urn:nasa:pds:<bundle_id>`
* collection LID / LIDVID  - `urn:nasa:pds:<bundle_id>:<collection_id>`
* product LID / LIDVID (for documents) - `urn:nasa:pds:<bundle_id>:<collection_id>:<product_id>`
* LIDVID - `LID::<version_id>

See DOI UI for how this is being handled over there for querying the the service.

Here is some logic for what I think needs to happen for the search:

For primary results at the top
```
if search by DOI / LID/ LIDVID not found:
    display "Exact match not found", and move onto related DOI section
```

For related DOI metadata (should include related DOIs even if an exact match is found):
```
if search by product LID / LIDVID `urn:nasa:pds:<bundle_id>:<collection_id>:<product_id>` not found:
    search for the parent collection DOI by removing the `<product_id>` from the LID/LIDVID: `urn:nasa:pds:<bundle_id>:<collection_id>`

if search by collection LID / LIDVID `urn:nasa:pds:<bundle_id>:<collection_id>` not found:
    search for the parent bundle DOI by removing the `<collection_id>` from the LID/LIDVID: `urn:nasa:pds:<bundle_id>`

if search by bundle LID / LIDVID not found: # currently wildcards are unsupported by API
    search for all child collections with `urn:nasa:pds:<bundle_id>:*` 
```

## Technical Info

How to connect to the validation API:

```
ssh -L 8085:localhost:8080 pds-dev3
```

See http://localhost:8085/PDS_APIs/pds_doi_api/0.1/ui/

### LINKED ISSUE #33: As a user, I want to search for a PDS identifier and associated metadata by DOI
...so i can use the DOI in a citation or trace back from a DOI to an associated bundle, collection, or product LID/LIDVID

## Details
Web page that displays all available DOIs in the PDS.

NOTE: As much as possible, let's try to replicate the search functionality implemented in the DOI UI.

### UI
Here is a quick wireframe of what I am thinking about the UI layout. This will go at https://pds.nasa.gov/datastandards/citing/doi .

### Search Functionality
Additionally, it should provide a basic search capability where a user can:
1. enter a DOI and get the resulting associated DOI metadata
2. enter a LID/LIDVID and get the results associated DOI metadata

 The LID or LIDVID can come in several forms:
* bundle LID / LIDVID - `urn:nasa:pds:<bundle_id>`
* collection LID / LIDVID  - `urn:nasa:pds:<bundle_id>:<collection_id>`
* product LID / LIDVID (for documents) - `urn:nasa:pds:<bundle_id>:<product_id>`

See DOI UI for how this is being handled over there for querying the the service.

Here is some logic for what I think needs to happen for the search:

For primary results at the top
```
if search by DOI / LID/ LIDVID not found:
    display "Exact match not found", and move onto related DOI section
```

For related DOI metadata (should include related DOIs even if an exact match is found):
```
if search by product LID / LIDVID `urn:nasa:pds:<bundle_id>:<collection_id>:<product_id>` not found:
    search for the parent collection DOI by removing the `<product_id>` from the LID/LIDVID: `urn:nasa:pds:<bundle_id>:<collection_id>`

if search by collection LID / LIDVID `urn:nasa:pds:<bundle_id>:<collection_id>` not found:
    search for the parent bundle DOI by removing the `<collection_id>` from the LID/LIDVID: `urn:nasa:pds:<bundle_id>`

if search by bundle LID / LIDVID not found:
    search for all child collections with `urn:nasa:pds:<bundle_id>:*`  # not sure if wildcards are possible through API
```

## Technical Info

How to connect to the validation API:

```
ssh -L 8085:localhost:8080 pds-dev3
```

See http://localhost:8085/PDS_APIs/pds_doi_api/0.1/ui/

Dependent upon #25

### PR DESCRIPTION
**Pull request by c-suh**
- Change default view to table of all identifiers
- Allow search by DOI or LIDVID or partial/term, e.g. "insight"
- Show associated identifiers
- Link to appropriate action (i.e. 'Release') for any listed identifier
- (Unrelated) Change Node input to select-dropdown for Release view

Resolves #25
Resolves #33

### CODE REVIEW

**Review by tloubrieu-jpl — CHANGES_REQUESTED** [review]
Thanks Catherine, that looks very good.

A few things I have noticed:
I cut and paste a URN from the table and search for it, but I had an answer No exact match.
image

I also tried with only the lid

image


The error might be on the API side or maybe we need clarification on how to handle multiple lidvid versions in the application. I don't think we discussed that yet.

Easier: We should have some text before the related DOIs list. That could be "Related DOIs" but it is @jordanpadams 's call.

At last, for the search box, I have the habit to press enter after I typed my search criteria and I was expecting that to search but here we need to click the magnifier. Would that be possible to also trigger search when a enter is pressed.

Overall this is good, and I believe you should present that to Jordan as early as possible to get his feedback. You can demo it for the sprint review but we might need more time to collect feedback.

**Comment by c-suh** [comment]
@tloubrieu-jpl
---
> I cut and paste a URN from the table and search for it, but I had an answer No exact match.

1. I had meant to seek clarification on this: are LIDVIDs (complete with a version) unique? And can one DOI be assigned to more than one LIDVID? The test data has several instances of multiple DOIs and multiple LIDVIDs, e.g.

| DOI | LIDVID |
| --- | ------- |
| 10.17189/29380 | 107::1.0 |
| 10.17189/29380 | 108::1.0 |
| | |
| 10.17189/29471 | urn:nasa:pds:lab_shocked_feldspars_3::3.0 |
| 10.17189/29474 | urn:nasa:pds:lab_shocked_feldspars_3::3.0 |

These answers to these two questions might require me to tweak the application logic.
---
> The error might be on the API side or maybe we need clarification on how to handle multiple lidvid versions in the application. I don't think we discussed that yet.

2. The multiple LIDVID versions is not something I recall discussing. The message saying "No exact match found" is how the application handles the search results. Let me know how you would like this changed.
---
> Easier: We should have some text before the related DOIs list. That could be "Related DOIs" but it is @jordanpadams 's call.
3.  @edwardbarraza's input could also be helpful here regarding usability and clearly conveying information.
---
> At last, for the search box, I have the habit to press enter after I typed my search criteria and I was expecting that to search but here we need to click the magnifier. Would that be possible to also trigger search when a enter is pressed.
4. Hitting `Tab` then `Enter` will trigger the search. Although not ideal, the behavior when you hit `Enter` (a refresh or reload of the application) is an existing bug that might warrant its own ticket, and due to time constraints (and no complaints or ticket), I left it as is. However, I would be happy to look into it.

**Comment by tloubrieu-jpl** [comment]
> ## @tloubrieu-jpl
> > I cut and paste a URN from the table and search for it, but I had an answer No exact match.
> 
> 1. I had meant to seek clarification on this: are LIDVIDs (complete with a version) unique? And can one DOI be assigned to more than one LIDVID? The test data has several instances of multiple DOIs and multiple LIDVIDs, e.g.
> 
> DOI	LIDVID
> 10.17189/29380	107::1.0
> 10.17189/29380	108::1.0
> 10.17189/29471	urn:nasa:pds:lab_shocked_feldspars_3::3.0
> 10.17189/29474	urn:nasa:pds:lab_shocked_feldspars_3::3.0


This should not happened. I think we need to check the backend behavior. I will create a ticket for that.

**Comment by tloubrieu-jpl** [comment]
@c-suh I made a quick test with the API being updated with the history of DOIs and I am realizing that there might be a mismatch in the status you expect and the one we have: the status 'Registered' is the one we use when the DOI is released. I this case we should be able to update the DOI from the table of DOIs. Is that something you considered yet ? I was thinking your code might expect 'Released' as a status or simply we forgot to mention that case before.

**Comment by c-suh** [comment]
Hi @tloubrieu-jpl! I was not aware of the status 'Registered' (or rather, I knew it as 'Released'), and I will update the code accordingly. I see the data and am excited to test with it and the new API version and will also look into the error you mentioned.

**Comment by c-suh** [comment]
@tloubrieu-jpl for all items which I've tried so far, I'm getting the same error.
- error name: `NoTransactionHistoryForLIDVIDException`
- error message: `Could not find an OSTI Label associated with LIDVID <lidvid>. The database and transaction history location may be out of sync. Please try resubmitting the record in reserve or draft.`

Also, I am aware of 4 status values but see only 2 in this new test data. Would it be possible to get a few which are also "Draft" and "In Review"?

**Comment by tloubrieu-jpl** [comment]
> @tloubrieu-jpl for all items which I've tried so far, I'm getting the same error.
> 
> * error name: `NoTransactionHistoryForLIDVIDException`
> * error message: `Could not find an OSTI Label associated with LIDVID <lidvid>. The database and transaction history location may be out of sync. Please try resubmitting the record in reserve or draft.`

You are right I missed to update the transaction history files. I will do it now.

> 
> Also, I am aware of 4 status values but see only 2 in this new test data. Would it be possible to get a few which are also "Draft" and "In Review"?


Since we generated the database from DOIs submitted at OSTI, they can only be in reserved or registered status. The other 'intermediary' status are not available in the OSTI database but only in Ron's system (he's managing the DOI registration process).

**Comment by tloubrieu-jpl** [comment]
@c-suh the api on pds-dev3 now works with the transaction history, I will do a few tests and I should be able to merge this pulll request.

**Review by tloubrieu-jpl — APPROVED** [review]
There are still things which do not work with the data history but this is unrelated to this pull request that I will merge so that we can move on. Thanks Catherine. That is a good work.

**Pull request merged**
