### PR TITLE
New Landing Page and Adjusted User Flow

### LINKED ISSUE #34: As a user, I want to see the error/warnings messages on the same page from where they were raised
The user will need to compare the error message with the actual data he has edited to understand better what need to be changed.

This is applicable to reserver, release/save and release/release actions.

While having the error/warning message on the form screen (reserve or release), we'll be careful to 2 things:
- not to move the preexisting widget in the screen because of the new message (eg on release/Save, now the SAVE,RELEASE buttons are pushed down when an error message appears)
- that the error message is clearly visible when it appear (e.g. not to have it on top of the screen while the user have scrolled down the screen to click on the button)

### LINKED ISSUE #44: Develop mock-ups for DOI Service Landing Page and Create Page

### LINKED ISSUE #47: As a user, I want the button to be "submit for review" when I am ready to submit my DOI for release
## Motivation
...so that it is consistent in the UI, and tells what actually is hapening.

## Additional Details

The button label is still "Release" when we click release on an existing DOI

image

## Acceptance Criteria

**When I perform** Release from an existing record
**Then I expect** the button label is "submit for reiview"

**When I perform** Release from a new record
**Then I expect** the button label is "submit for reiview"

### PR DESCRIPTION
**Pull request by c-suh**
- Resolves #34
- Resolves #44 
- Resolves #47 
- Partially addresses #48
- Possibly addresses #41

### CODE REVIEW

**Review by eddiesarevalo — APPROVED** [review]

**Review by eddiesarevalo — CHANGES_REQUESTED** [review]
It is looking good. Just a couple of things if possible before we merge to main branch.

- [ ] Remove the commented code. If it isn't going to be used we should delete it to avoid confusion and clutter in the future.

- [ ] Stick to Material-UI's style solution for consistency. Instead of using the global CSS file use [make styles](https://material-ui.com/styles/basics/)

- [ ] Extend this component to fill out the page so that the page won't have a double scroll. It seems a bit awkward to have double scrolls when its not necessary.
Screen Shot 2021-06-01 at 11 29 59 AM

**Comment by jordanpadams** [comment]
@c-suh see @eddiesarevalo's comments above.

**Comment by tloubrieu-jpl** [comment]
Thanks @eddiesarevalo for your review. Since @gxtchen is doing the I&T test now, I will merge the branch as-is and a new ticket for your request for updates.

**Review by tloubrieu-jpl — APPROVED** [review]
I am approving so to merge in master. Change requests are in ticket https://github.com/NASA-PDS/pds-doi-ui/issues/56

**Pull request merged**
