### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by c-suh**
Resolves https://github.com/NASA-PDS/pds-doi-ui/issues/31
Resolves https://github.com/NASA-PDS/pds-doi-ui/issues/30

### CODE REVIEW

**Comment by c-suh** [comment]
If a style change is desired, I can do so before merging this into the master branch. Or shall I keep the work done during Eddie's leave on a separate branch?

**Review by tloubrieu-jpl — CHANGES_REQUESTED** [review]
Thanks @c-suh that works.

Just one thing. In other error messages Eddie had them in a different screen (see release). It is not that I prefer one option or the other (warning/error on same screen) but we will need to have that to be consistent in the application. Would that be complicated to have this behavior for the SAVE errors ?

Note that the demo tomorrow is cancelled since Jordan thinks that the UI is not mature enough yet. So no hurry here, finally.

**Comment by c-suh** [comment]
@tloubrieu-jpl I do not think it is any more complicated. My preference would be to have it on the same screen so that the user, without having to navigate/click back to the editable information, would have the opportunity to fix and attempt another save. However, I agree with you that consistency is important and will make this match the existing user flow.

Thank you for the heads up about the cancelled demo! I will still aim to complete this task within the current sprint.

**Comment by tloubrieu-jpl** [comment]
@c-suh yes, that is better to have the warning on the same page, so that users can see what the error related to. So you can leave that way for the SAVE button. I will create a ticket to update the warning/error display for reserve and release.

**Pull request merged**
