### PR TITLE
Address requested changes on closed PR and Iterative enhancements

### LINKED ISSUE #48: Enhancements per initial implementation of mockups
Here some updates to be implemented to the initial dev completed for #44 

- [x] Change “Get URL” to “Upload Label”
- [x] Add "Upload Label" button next to text box
- [x] "Save" and "Submit for Review" buttons side-by-side
- [x] Add DOI(s) returned from Reserve step to output message
- [x] Update API requests per latest changes to https://miro.com/app/board/o9J_lF_ReJo=/
    - [x] `Save` button -> `POST /dois with action=draft`
    - [x] `Submit for Review` button -> `POST /dois with action=draft` AND `POST /dois/{lidvid}/submit to submit for review`
- [x] Update "Nodes" dropdown to be "Node" (the dropdown contains all the nodes, but the user is inputting their Node)

### LINKED ISSUE #50: Add additional help information throughout DOI UI
Add info (something like ℹ️ ) icons on following pages / sections with the following text:

- [x] `Keywords` text box - _These keywords may be used to enable future discovery of these datasets. The auto-complete values are populated by the [Unified Astronomy Thesaurus](https://astrothesaurus.org/). Additional custom keywords may also be entered._
    - [ ]  while updating that, also update to have text completion lineup with the cursor in the text box

- [x] On `Create DOI` page, below "Ignore Warnings" checkbox, add text "Questions about process or information requested? See [FAQs](https://github.com/NASA-PDS/pds-doi-service/blob/master/docs/support/faqs.md) or contact the [PDS Operator](mailto:pds-operator@jpl.nasa.gov) for assistance." For the FAQ page and email address, let's make sure we add the applicable icons to indicate they will be leaving the interface, and open in a new window.

### LINKED ISSUE #54: Update Release and Update DOI pages to follow similar design as Create DOI page
# Release DOI

**When I click on the release button for urn:nasa:pds:insight_hp3_tem:**

Screen Shot 2021-06-02 at 10 19 57 AM

**what I would like to see is something that looks very similar to the create DOI page.**

Screen Shot 2021-06-02 at 10 27 42 AM

**If they select `Yes`:**

Screen Shot 2021-06-02 at 10 21 59 AM

**If they select `No`, display the following text in a red error box:**
> The data must registered with PDS Engineering Node and made publicly available prior to the release of the DOI. See [FAQs](https://github.com/NASA-PDS/pds-doi-service/blob/master/docs/support/faqs.md) for more information.

---

# Update DOI

Same interface as `Release DOI`.

### LINKED ISSUE #56: Update to DOI UI code per pull request #51 comments
From @eddiesarevalo :

It is looking good. Just a couple of things if possible before we merge to main branch.

- [x]  Remove the commented code. If it isn't going to be used we should delete it to avoid confusion and clutter in the future.

- [x]  Stick to Material-UI's style solution for consistency. Instead of using the global CSS file use make styles

- [x]  Extend this component to fill out the page so that the page won't have a double scroll. It seems a bit awkward to have double scrolls when its not necessary.

Screen Shot 2021-06-01 at 11 29 59 AM

### PR DESCRIPTION
**Pull request by c-suh**
Resolves #56
- Remove comments and unused imports and variables
- Move styling from global CSS to within individual files with makeStyles
- Remove outer scroll from page with search results

---
Resolves #48
- Change text to 'Upload URL'
- Move buttons to be inline (Upload URL to input, Save to Submit)

---
Resolves #50 
- Add `i` icon and text for Keywords text box
- Add `i` icon and text for general questions about process or information requested

---
Resolves #54 
- Have Update/Release page follow design similar to Create
  - Submitter and Node at top
  - Question asking if publicly available
  - option to upload metadata by PDS4 Label URL
- Add DOI of item at top of page in disabled/non-clickable field

---
Misc request
- Remove word 'Error' from error or warning alerts

### CODE REVIEW

**Review by tloubrieu-jpl — APPROVED** [review]
That works for me. Thanks Catherine for the quick update.

I am waiting for @eddiesarevalo review on the code details before I merge.

Thanks

**Comment by c-suh** [comment]
I've also pushed for this PR the remaining items from https://github.com/NASA-PDS/pds-doi-ui/issues/48. @eddiesarevalo let me know how these look. Thank you!

**Comment by c-suh** [comment]
Latest push (https://github.com/NASA-PDS/pds-doi-ui/pull/57/commits/1a404f5ed6a54b92a0d721de4c3d368e7931b8a2) resolves issue #54

**Comment by jordanpadams** [comment]
@eddiesarevalo since this PR is addressing issues you raised, I will leave it to you to approve and merge.

**Comment by c-suh** [comment]
@jordanpadams sorry, I might have misunderstood from our meetings a couple weeks ago. I thought these issues minor enough to keep working on the same branch so as to fold into one PR:
- https://github.com/NASA-PDS/pds-doi-ui/issues/56 (Eddie's requested changes from a previous PR)
- https://github.com/NASA-PDS/pds-doi-ui/issues/48 (Enhancements per initial implementation of mockups)(rest of)
- https://github.com/NASA-PDS/pds-doi-ui/issues/54 (Update Release and Update DOI pages to follow similar design as Create DOI page)
- https://github.com/NASA-PDS/pds-doi-ui/issues/50 (Add additional help information throughout DOI UI)(in progress and will be done today)

Should I rename this PR and edit the initial description, or rebase this branch and force-push then create separate branches and PRs for the other 3 items?

**Comment by c-suh** [comment]
@NASA-PDS/pdsen-ui-committers, this PR will not have any more pushes and is ready to be reviewed and hopefully closed this sprint.

**Review by eddiesarevalo — APPROVED** [review]
All the changes were made, thanks @c-suh!

**Comment by tloubrieu-jpl** [comment]
Merged in branch routing-fixes

**Pull request closed without merging**
